<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">

<HTML>

<HEAD>
<TITLE>A.I.D. - Album Information Database</TITLE>
</HEAD>

<BODY BGCOLOR="#000000" TEXT="#c0c0c0" LINK="#FFFFFF" VLINK="#c0c0c0" ALINK="#00FFFF"><FONT FACE="Verdana" SIZE=3><?php_track_vars?><FORM method="POST" action="create.phtml"><INPUT
type="TEXT" name="artistalbum"><BR><BR><TABLE  width="40%" border="0" cellspacing="1" cellpadding="1" bgcolor="#808080"><TR>
<TH>Track Name</TH><TH>Track Length</TH><TH>Track BPM</TH></TR>

<?php
for ($i = 0 ; $i <$numoftracks; $i++) {
	echo "<tr><td align=center><input type=\"text\" name=\"trackname[]\" size=\"50\" maxlength=\"50\"></td>
	<td align=center><input type=\"text\" name=\"tracklength[]\" size=\"5\" maxlength=\"5\"></td>
	<td align=center><input type=\"text\" name=\"trackbpm[]\" size=\"6\" maxlength=\"6\"></td>
	</tr>";
}
?></TABLE><BR><INPUT type="submit" value="Submit Album"></FORM>

</BODY>

</HTML>
